# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
  sha: v2.1.0
  hooks:
    - id: epp-validate
    - id: erb-validate
    - id: puppet-lint
      args:
        - --fail-on-warnings
        - --no-140chars-check
        - --no-documentation-check
        - --no-puppet_url_without_modules-check
    - id: puppet-validate
    - id: ruby-validate
- repo: https://github.com/SineQuaNonSoftware/workflows/
  rev: master
  hooks:
    - id: puppet-forge-github-actions
