version: 2.1

orbs:
  bits-puppet: broadinstitute/bits-puppet@0.1.1

executors:
  puppet5: bits-puppet/ruby_puppet
    puppet_version: '< 6.0.0'
    ruby_version: '2.4.5'
  puppet6: bits-puppet/ruby_puppet
    puppet_version: '< 7.0.0'
    ruby_version: '2.5.7'

workflows:
  build_and_publish:
    jobs:
      - bits-puppet/static:
      - bits-puppet/run-tests:
          requires:
            - bits-puppet/static
      - bits-puppet/deploy:
          requires:
            - bits-puppet/run-tests