version: 2.1

orbs:
  bits-puppet: broadinstitute/bits-puppet@0.1.1

executors:
  my-executor: bits-puppet/ruby_puppet

workflows:
  build_and_publish:
    jobs:
      - bits-puppet/static:
          puppet_version: < 6.0.0
          ruby_version: 2.4.5
      - bits-puppet/run-tests:
          puppet_version: < 6.0.0
          ruby_version: 2.4.5
          requires:
            - bits-puppet/static
      - bits-puppet/deploy:
          requires:
            - bits-puppet/run-tests