version: 2.1

orbs:
  bits-puppet: broadinstitute/bits-puppet@0.1.1

executors:
  puppet5: bits-puppet/ruby_puppet

workflows:
  build_and_publish:
    jobs:
      - bits-puppet/static:
      - bits-puppet/run-tests:
          requires:
            - bits-puppet/static
      - bits-puppet/deploy:
          requires:
            - bits-puppet/run-tests