---
version: 2.1

orbs:
  bits-puppet: broadinstitute/bits-puppet@0.1.1

workflows:
  build_and_deploy:
    - bits-puppet/static
    - bits-puppet/run-tests:
        requires:
          - bits-puppet/static
    - bits-puppet/deploy:
        requires:
          - bits-puppet/run-tests    