name: Valid for Puppet 6 through 7 and published on the Forge
on: [push, pull_request]

jobs:
  build_puppet6:
    name: Validate for Puppet 6
    runs-on: ubuntu-latest
    env:
      PUPPET_GEM_VERSION: '~> 6'
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.7
        bundler-cache: true
    - name: Display the versions used
      run: ruby --version && echo -n 'gem ' && gem --version && bundle --version
    - name: Syntax check
      run: bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
    - name: Test suite
      run: bundle exec rake parallel_spec

  build_puppet7:
    name: Validate for Puppet 7
    runs-on: ubuntu-latest
    env:
      PUPPET_GEM_VERSION: '~> 7'
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.6
        bundler-cache: true
    - name: Display the versions used
      run: ruby --version && echo -n 'gem ' && gem --version && bundle --version
    - name: Syntax check
      run: bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
    - name: Test suite
      run: bundle exec rake parallel_spec

  build_forge:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    name: Build and publish to Puppet Forge
    runs-on: ubuntu-latest
    needs: [ build_puppet6, build_puppet7 ]
    steps:
    - name: Get latest tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF:10}
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.vars.outputs.tag }}
    - name: Build and publish module
      uses: barnumbirr/action-forge-publish@v2.9.0
      env:
       FORGE_API_KEY: ${{ secrets.FORGE_API_KEY }}
       REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
