name: Syntax checks
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ruby:2.4.5
    steps:
      - name: Install bundler
        run: gem install bundler
      - name: Display the versions used
        run: ruby --version && echo -n 'gem ' && gem --version && bundle --version
      - name: Force update gems
        run: rm Gemfile.lock || true
      - name: Install dependencies
        run: bundle install --without system_tests --path /github/workspace/gems --jobs $(nproc)
      - name: Syntax check
        run: bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop